### PR TITLE
Backup the unmodified current line and restore before applying `textEdit`.

### PR DESCRIPTION
**Pull request by scturtle**

### CODE REVIEW

**Comment by tigersoldier** [comment]
So the change is to fix the bug that `textEdit` is applied with `label` inserted, right? If that's the case how about simply removing the inserted `label` as what `insertText` does? There is a potential bug that if the inserted `label` has multiple lines, backing up the current line is not enough.

**Comment by scturtle** [comment]
Not sure how to revert the insertion. Only one `candidate` string is passed to the post completion function.  Maybe backup more things to lookup later?

**Comment by tigersoldier** [comment]
This is how `insertText` handles it (just a few lines below your change:

```elisp
       (cl-assert (string-equal (buffer-substring-no-properties start (point)) label))
       (goto-char start)
       (delete-char (length label))
```

The idea is `label` is the text inserted by company. Go back, delete, and done.

You can extract this logic to a function `company-lsp--revert-candidate-label`.

**Comment by scturtle** [comment]
The problem is: if you deleted the whole label you also deleted the prefix, and no further `editText` can be applied on it.

**Comment by scturtle** [comment]
In the specification:
```
	/**
	 * An edit which is applied to a document when selecting this completion. When an edit is provided the value of
	 * `insertText` is ignored.
	 *
	 * *Note:* The range of the edit must be a single line range and it must contain the position at which completion
	 * has been requested.
	 */
	textEdit?: TextEdit;
```
I think it assumes a single line modification.

**Comment by tigersoldier** [comment]
That's a good point. So simply deleting the label is incorrect and keeping the current line is necessary.

**Pull request merged**
